# Use the specified image
FROM mcr.microsoft.com/devcontainers/universal:2

# Install Azure CLI
RUN curl -sL https://aka.ms/InstallAzureCLIDeb | bash

# Set the default shell to bash rather than sh
ENV SHELL /bin/bash