---
# yaml-language-server: $schema=config.schema.json
# name of the cluster
project_name: az-hop

location: eastus
resource_group: azhop-rg
use_existing_rg: false

anf:
  create: true
  # Size of the ANF pool and unique volume
  homefs_size_tb: 4
  # Service level of the ANF volume, can be: Standard, Premium, Ultra
  homefs_service_level: Standard
  dual_protocol: false # true to enable SMB support. false by default
  alert_threshold: 80 # alert when ANF volume reaches this threshold

optout_telemetry: true

tags:
  env: dev
  project: azhop
  scheduler: slurm

mounts:
  # mount settings for the user home directory
  home:
    type: anf # anf or azurefiles, default to anf. One of the two should be defined in order to mount the home directory
    mountpoint: /anfhome # /sharedhome for example
    server: '{{anf_home_ip}}' # Specify an existing NFS server name or IP, when using the ANF built in use '{{anf_home_ip}}'
    export: '{{anf_home_path}}' # Specify an existing NFS export directory, when using the ANF built in use '{{anf_home_path}}'
    options: '{{anf_home_opts}}'

admin_user: hpcadmin

network:
  # Create Network and Application Security Rules, true by default, false when using an existing VNET if not specified
  create_nsg: true
  vnet:
    name: hpcvnet # Optional - default to hpcvnet
    #id: # If a vnet id is set then no network will be created and the provided vnet will be used
    address_space: "10.25.0.0/23" # Optional - default to "10.0.0.0/16"
    # When using an existing VNET, only the subnet names will be used and not the adress_prefixes
    subnets: # all subnets are optionals
    # name values can be used to rename the default to specific names, address_prefixes to change the IP ranges to be used
    # All values below are the default values
      frontend: 
        name: frontend
        address_prefixes: "10.25.0.0/29"
        create: true # create the subnet if true. default to true when not specified, default to false if using an existing VNET when not specified
      ad:
        name: ad
        address_prefixes: "10.25.0.8/29"
        create: true
      admin:
        name: admin
        address_prefixes: "10.25.0.16/28"
        create: true
      netapp:
        name: netapp
        address_prefixes: "10.25.0.32/28"
        create: true
      lustre: # Lustre subnet when deploying a lustre filesystem
        address_prefixes: "10.25.0.128/26"
        create: true
      # the outbounddns is optional and only when deploying an Azure Private DNS Resolver
      # outbounddns:
      #   name: outbounddns
      #   address_prefixes: "10.25.0.48/28"
      #   create: true
      # gateway: # Gateway subnet name is always fixed to GatewaySubnet
      #   address_prefixes: "10.25.0.128/27" # Recommendation is to use /27 network
      #   create: true
      # bastion: # Bastion subnet name is always fixed to AzureBastionSubnet
      #   address_prefixes: "10.25.0.64/26" # CIDR minimal range must be /26
      #   create: true
      compute:
        name: compute
        address_prefixes: "10.25.1.0/24"
        create: true

# NAT Gateway is used for outbound internet connectivity
nat_gateway:
  create: false

# Base image configuration. Can be either an image reference or an image_id from the image registry or a custom managed image
linux_base_image: "OpenLogic:CentOS:7_9-gen2:latest" # publisher:offer:sku:version or image_id
windows_base_image: "MicrosoftWindowsServer:WindowsServer:2019-Datacenter-smalldisk:latest" # publisher:offer:sku:version or image_id

jumpbox:
  vm_size: Standard_B2ms
  ssh_port: 8822 # SSH port used on the public IP, default to 22
  name: jumpbox

ad:
  vm_size: Standard_B2ms
  name: ad

authentication:
  user_auth: ad # local or ad
  httpd_auth: basic # oidc or basic

private_dns:
  create: true # Create a private DNS zone for the environment. Default to false
  name: hpc.azure # Name of the private DNS zone to be created. Default to hpc.azure
  registration_enabled: false # Enable auto-registration of VMs in the private DNS zone. Default to false

ondemand:
  vm_size: Standard_D4s_v5
  generate_certificate: true
  name: ondemand
grafana:
  vm_size: Standard_B2ms
  name: grafana
scheduler:
  vm_size: Standard_B2ms
  name: scheduler
cyclecloud:
  vm_size: Standard_B2ms
  name: ccportal

users:
  - { name: hpcuser, uid: 10001 }
  - { name: adminuser, uid: 10002, groups: [5001, 5002] }
  - { name: tim.tim, uid: 10003 }

usergroups:
  - name: azhop-users # All users will be added to this one by default
    gid: 5000
  - name: azhop-admins # For users with azhop admin privilege
    gid: 5001
    description: "For users with azhop admin privileges"
  - name: azhop-localadmins # For users with sudo right on nodes
    gid: 5002
    description: "For users with sudo right or local admin right on nodes"

# scheduler to be installed and configured
queue_manager: slurm

# Specific SLURM configuration
slurm:
  # Enable SLURM accounting, this will create a SLURM accounting database in a managed MySQL server instance
  accounting_enabled: false
  # SLURM version to install.
  slurm_version: 22.05.3
  cyclecloud_slurm_verion: 2.7.2
  # cluster_name: slurm_azhop



  # Define an ANF account, single pool and volume
# If not present assume that there is an existing NFS share for the users home directory

# Enable cvmfs-eessi - disabled by default
cvmfs_eessi:
  enabled: true

enroot:
  enroot_version: 3.4.1

# If using an existing Managed MariaDB instance for SLURM accounting, specify these values
database:
  # Admin user of the database for which the password will be retrieved from the azhop keyvault
  user: sqladmin
  # FQDN of the managed instance
  #fqdn:
  # IP of the managed private endpoint if the FQDN is not registered in a private DNS
  #ip: 

# Autoscale default settings for all queues, can be overriden on each queue depending on the VM type if needed
autoscale:
  idle_timeout: 1800 # Idle time in seconds before shutting down VMs - default to 1800 like in CycleCloud


queues:
  - name: htc
    vm_size: Standard_F2s_v2
    max_core_count: 8 #128
    image: azhpc:azhop-compute:centos-7_9:latest
    ColocateNodes: false

  - name: hpc
    vm_size: Standard_HB120rs_v3
    max_core_count: 16 #480
    image: azhpc:azhop-compute:centos-7_9:latest
    EnableAcceleratedNetworking: true
  - name: viz3d
    type: remoteviz
    description: "With GPU - Small GPU node for single session"
    vm_size: Standard_NV12s_v3
    max_core_count: 2 #24
    image: azhpc:azhop-desktop:centos-7_9:latest
    ColocateNodes: false
    EnableAcceleratedNetworking: true
    # Queue dedicated to share GPU remote viz nodes. This name is fixed and can't be changed
  - name: largeviz3d
    vm_size: Standard_NV48s_v3
    max_core_count: 4 #48
    image: azhpc:azhop-desktop:centos-7_9:latest
    ColocateNodes: false
    EnableAcceleratedNetworking: true
    # Queue dedicated to non GPU remote viz nodes. This name is fixed and can't be changed
  - name: viz
    vm_size: Standard_D8s_v5
    max_core_count: 4 #32
    image: azhpc:azhop-desktop:centos-7_9:latest
    ColocateNodes: false
    EnableAcceleratedNetworking: true
    max_hours: 12 # Maximum session duration
    min_hours: 1 # Minimum session duration - 0 is infinite



# Application settings
applications:
  bc_codeserver:
    enabled: true
  bc_jupyter:
    enabled: true
# Option to install the monitoring agent on static infra VMs. Can be disabled if the agent is installed by policy.  
monitoring: 
  azure_monitor_agent: false # Install Azure Monitor Agent on static infra VMs
  # Optional settings to deploy Grafana and install Telegraf
  telegraf: true # Install telegraf on static infra VMs and dynamic compute nodes. Default: true
  grafana: true # Deploy a Grafana instance with pre-defined dashboards. Default: true
